name: Build Node binaries for Alpine

on:
  workflow_dispatch:

jobs:
  alpine-x64:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        target-node: [8, 10, 12, 14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PKG_FETCH_OPTION_n=node${{ matrix.target-node }}
          context: .
          file: ./Dockerfile.alpine
          platforms: alpine/amd64
          outputs: type=tar,dest=../out.tar

      - name: Extract binaries from Docker image
        run: |
          tar xvf ../out.tar root/pkg-fetch/dist

      - uses: actions/upload-artifact@v2
        with:
          name: node${{ matrix.target-node }}-alpine-x64
          path: root/pkg-fetch/dist/*
